import type { ChecklistItem } from "src/app/types";

const DAILY_CLEANING_ID = "e52f0220-aff1-4344-b944-a08a4c29a04d";

export const DAILY_CLEANING_TEMPLATE: ChecklistItem[] = [
    {
        itemType: "checklist-item",
        isHidden: false,
        id: DAILY_CLEANING_ID,
        text: "Daily Cleaning",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 0,
        tabSortOrder: { today: 0 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: true,
        parentUuid: null,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "aef8d2fe-c917-4e53-81fd-08c24ce20b13",
        text: "Wipe counters",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 0,
        tabSortOrder: { today: 1 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "c218ba2d-5661-4e7d-af6d-efad18a9102a",
        text: "Make beds",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 1,
        tabSortOrder: { today: 2 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "a3efcf04-220b-441f-8a00-c84444e2a8e4",
        text: "Wash dishes",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 2,
        tabSortOrder: { today: 3 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "60564a2e-6f6f-43d0-a127-19f353dfdd55",
        text: "One load of laundry",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 3,
        tabSortOrder: { today: 4 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "4493325e-3c4f-413f-86aa-b85d04859e7d",
        text: "Take out trash",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 4,
        tabSortOrder: { today: 5 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
    {
        itemType: "checklist-item",
        isHidden: false,
        id: "ed2843eb-14da-4748-affd-eb14dd5b2eb5",
        text: "Clean kitchen floor in the evening",
        done: false,
        lastCompleted: "",
        note: "",
        sortOrder: 5,
        tabSortOrder: { today: 6 },
        category: "housework",
        mode: "daily",
        isPriority: false,
        isArchived: false,
        hasSubChores: false,
        parentUuid: DAILY_CLEANING_ID,
        recurrence: null,
        nextDue: null,
    },
];
