import { type ChecklistItem } from "src/app/types";

const now = new Date();
const twoDaysFromNow = new Date(now);
twoDaysFromNow.setDate(twoDaysFromNow.getDate() + 2);

export const DEMO_TASKS: ChecklistItem[] = [
    {
        itemType: 'checklist-item',
        id: "1",
        text: "Put your thoughts somewhere safe",
        done: false,
        lastCompleted: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days ago
        note: "",
        sortOrder: 0,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "daily",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "2",
        text: "Tap to check something off",
        done: false,
        lastCompleted: "",
        note: "Nothing bad happens if you leave it unfinished.",
        sortOrder: 1,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "occasional",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "3",
        text: "Mark one thing as important",
        done: false,
        lastCompleted: "",
        note: "Priority just means this matters a little more today.",
        sortOrder: 2,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "one-time",
        isPriority: true,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "4",
        text: "Break something into smaller steps",
        done: false,
        lastCompleted: "",
        note: "You can add subtasks if a task feels too big.",
        sortOrder: 3,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "one-time",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: true,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "5",
        text: "Drag tasks into the order that feels right",
        done: false,
        lastCompleted: "",
        note: "There is no perfect order. Just what helps now.",
        sortOrder: 4,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "one-time",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "6",
        text: "Hide this task for today",
        done: false,
        lastCompleted: "",
        note: "Hiding doesn't delete it. It just gives today some breathing room. You can revisit it tomorrow.",
        sortOrder: 5,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "one-time",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: true,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "7",
        text: "Example subtask: choose one tiny next step",
        done: false,
        lastCompleted: "",
        note: "Subtasks help reduce overwhelm.",
        sortOrder: 0,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "one-time",
        isPriority: false,
        isArchived: false,
        parentUuid: "4",
        hasSubChores: false,
        isHidden: false,
        recurrence: null,
        nextDue: null
    },
    {
        itemType: 'checklist-item',
        id: "8",
        text: "Example task with due date in two days",
        done: false,
        lastCompleted: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        note: "This demonstrates seeded last-completed and due fields.",
        sortOrder: 6,
        tabSortOrder: {},
        category: "",
        categoryUuid: null,
        mode: "occasional",
        isPriority: false,
        isArchived: false,
        parentUuid: null,
        hasSubChores: false,
        isHidden: false,
        recurrence: {
            type: "interval",
            count: 1,
            frequency: "daily",
            startDate: '2024-01-01T00:00:00.000Z'
        },
        nextDue: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString() // + 2 days
    }
];
